export const colors = [
  'aqua',
  'black',
  'blue',
  'fushsia',
  'gray',
  'green',
  'lime',
  'maroon',
  'navy',
  'olive',
  'red',
  'silver',
  'teal',
  'white',
  'yellow',
]

export const names = [
  'Samuel Galloway',
  'Nathanael Sawyer',
  'Nichola Stark',
  'Sabah Reeve',
  'Aleksander Nieves',
  'Ansh Corrigan',
  'Ellesha Mcdermott',
  'Terrence Reid',
  'Zakk Krueger',
  'Zoë Everett',
  'Rupert Knight',
  'Fenella Doyle',
]

export const posts = [
  { userId: 1, id: 1, title: 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit' },
  { userId: 2, id: 2, title: 'qui est esse' },
  { userId: 1, id: 3, title: 'ea molestias quasi exercitationem repellat qui ipsa sit aut' },
  { userId: 4, id: 4, title: 'eum et est occaecati' },
  { userId: 1, id: 5, title: 'nesciunt quas odio' },
  { userId: 1, id: 6, title: 'dolorem eum magni eos aperiam quia' },
  { userId: 3, id: 7, title: 'magnam facilis autem' },
  { userId: 1, id: 8, title: 'dolorem dolore est ipsam' },
  { userId: 3, id: 9, title: 'nesciunt iure omnis dolorem tempora et accusantium' },
  { userId: 1, id: 10, title: 'optio molestias id quia eum' },
]
